"""Init migration

Revision ID: 3d93148c2fa6
Revises: 
Create Date: 2024-05-04 18:40:30.618669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d93148c2fa6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ka', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ka', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ka', sa.String(length=255), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('title_ka', sa.String(length=255), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ka', sa.Text(), nullable=True),
    sa.Column('start', sa.TIMESTAMP(), nullable=True),
    sa.Column('end', sa.TIMESTAMP(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outages')
    op.drop_table('streets')
    op.drop_table('districts')
    op.drop_table('cities')
    # ### end Alembic commands ###
