"""Add osm_id col to street model

Revision ID: 66f2e67a36df
Revises: d0d1c59e518c
Create Date: 2024-05-06 22:14:52.812773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f2e67a36df'
down_revision: Union[str, None] = 'd0d1c59e518c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('street', sa.Column('osm_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('street', 'osm_id')
    # ### end Alembic commands ###
